### ISSUE TITLE
A bit sorry,but I want to know how p backward,most of code dont implement,instead only set p =3

### ISSUE THREAD

**Issue by zzk2021** [mxsurui/GemPooling_Pytorch#1]

**Comment by Strand2013** [comment]
p is a learnable parameter，the initiate value of p is 3，the progress of backward is same to other parameter，like linear or conv.

**Comment by zzk2021** [comment]
> p is a learnable parameter，the initiate value of p is 3，the progress of backward is same to other parameter，like linear or conv.

Thanks for your  reminding, now I know how to work
